//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFORTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Idea
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string IdeaText { get; set; }
        public string Author { get; set; }
        public Nullable<int> deleted { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime LastEdit { get; set; }
    }
}
